version: '3.8'

services:
  # PHP service with SQLite
  php:
    image: php:8.2-fpm
    container_name: php_app
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/html
      - database_volume:/var/www/database
    environment:
      - SQLITE_DATABASE_PATH=/var/www/database/database.sqlite
    networks:
      - app-network
    user: www-data

  # Nginx web server
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database_volume:
    driver: local 